@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU3MzYzM2U1LTRiZjAtNGE3MC04NjkzLTU0NjEyYTQ0NzIwOSIsImlhdCI6MTcyMTE0MDA2OSwiZXhwIjoxNzIxNDg1NjY5fQ.BNln2a0Dl_tMJhx2hpp6kk-IG6881K4Ot8BWG1W8bLQ

//login
###
POST http://localhost:5006/login
Content-Type: application/json

{
    "username" : "admin",
    "password" : "Admin1234!"
}

###
GET http://localhost:5006/monitoring/2148
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET http://localhost:5006/count-dashboard
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET http://localhost:5006/list-sensor?id=2139
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET http://localhost:5006/akses-point
Content-Type: application/json
Authorization: Bearer {{token}}


//Historicdata-csv
###
GET http://localhost:5006/historicdata-csv?id=2069&avg=3600&sdate=2024-07-13-00-00-00&edate=2024-07-14-00-00-00&usecaption=1
Content-Type: application/json
Authorization: Bearer {{token}}

//Historicdata-html
###
GET http://localhost:5006/historicdata-html?id=2069&sdate=2024-07-13-08-23-00&edate=2024-07-14-08-23-00&avg=3600&pctavg=300&pctshow=false&pct=95&pctmode=false&hide=NaN
Content-Type: application/json
Authorization: Bearer {{token}}

//GET SVG
###
GET http://localhost:5006/get-svg?type=graph&graphid=0&id=2069&graphstyling=showLegend%3D%271%27+baseFontSize%3D%275%27 
Content-Type: application/json
Authorization: Bearer {{token}} 

//table JSON
//QUERY ATAU PARAMS
# content
# columns
# filter_device
# filter_type
# output
# sensor_id
# filter_session
# count
# noraw
# id
# usecaption
# filter_user

#type
#listdevice
#listsensor
# datavalues

# ###
# GET http://localhost:5006/table-json/listdevice?http://127.0.0.1/api/table.json?content=devices&&usecaption=true&filter_parentid=2067&columns=objid,device
# Content-Type: application/json
# Authorization: Bearer {{token}}

//table XML
//QUERY ATAU PARAMS
# content
# id
###
# GET http://localhost:5006/table-xml?content=
# Content-Type: application/json
# Authorization: Bearer {{token}}

//detail sensor
//QUERY ATAU PARAMS
# id
# ###
# GET http://localhost:5006/detail-sensor?id=2080&usecaption=true
# Content-Type: application/json
# Authorization: Bearer {{token}}

