@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI5ZGFjNTlkLWQ4MjItNDFiNy04OGZjLWVmMmQ2ZjJjNzk2NCIsImlhdCI6MTcyMTQ1OTM4MiwiZXhwIjoxNzIxODA0OTgyfQ.tdGlkncv5EHZ_-Aa9duafKOe-FOBnmtyUJXj4QS8tbY

//login
###
POST http://localhost:5006/login
Content-Type: application/json

{
    "username" : "admin",
    "password" : "Admin1234!"
}

//loregister
###
POST http://localhost:5006/register
Content-Type: application/json

{
    "username" : "admin",
    "password" : "Admin1234!"
}

###
GET http://localhost:5006/monitoring/2152
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET http://localhost:5006/count-dashboard
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET http://localhost:5006/list-sensor?id=2139
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET http://localhost:5006/akses-point
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET http://localhost:5006/list-group-id
Content-Type: application/json
Authorization: Bearer {{token}}


//Type daily,weekly,monthly

//Historicdata-csv
###
GET http://localhost:5006/historicdata-csv/monthly?id=2154
Content-Type: application/json
Authorization: Bearer {{token}}

//Type daily or weekly
//Historicdata-html
###
GET http://localhost:5006/historicdata-html/monthly?id=2154
Content-Type: application/json
Authorization: Bearer {{token}}

//GET SVG
###
GET http://localhost:5006/get-svg?type=graph&graphid=0&id=2069&graphstyling=showLegend%3D%271%27+baseFontSize%3D%275%27 
Content-Type: application/json
Authorization: Bearer {{token}} 

//table JSON
//QUERY ATAU PARAMS
# content
# columns
# filter_device
# filter_type
# output
# sensor_id
# filter_session
# count
# noraw
# id
# usecaption
# filter_user

#type
#listdevice
#listsensor
# datavalues

# ###
# GET http://localhost:5006/table-json/listdevice?http://127.0.0.1/api/table.json?content=devices&&usecaption=true&filter_parentid=2067&columns=objid,device
# Content-Type: application/json
# Authorization: Bearer {{token}}

//table XML
//QUERY ATAU PARAMS
# content
# id
###
# GET http://localhost:5006/table-xml?content=
# Content-Type: application/json
# Authorization: Bearer {{token}}

//detail sensor
//QUERY ATAU PARAMS
# id
# ###
# GET http://localhost:5006/detail-sensor?id=2080&usecaption=true
# Content-Type: application/json
# Authorization: Bearer {{token}}

