@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFhMGZmMzM4LTk3ZjUtNDBjMC1hZjVkLTQ0NjhjNGEwZTQ3OCIsImlhdCI6MTcyMDgzNTg4MCwiZXhwIjoxNzIxMTgxNDgwfQ.oQiZU1i4lMYzkpseh4kPI6v3en-N2oW0JcE_X0w989E

//login
###
POST http://localhost:5006/login
Content-Type: application/json

{
    "username" : "admin",
    "password" : "Admin1234!"
}

//table JSON
//QUERY ATAU PARAMS
# content
# columns
# filter_device
# filter_type
# output
# sensor_id
# filter_session
# count
# noraw
# id
# usecaption
# filter_user

#type
#listdevice
#listsensor
# datavalues

###
GET http://localhost:5006/table-json/listdevice?http://127.0.0.1/api/table.json?content=devices&&usecaption=true&filter_parentid=2067&columns=objid,device
Content-Type: application/json
Authorization: Bearer {{token}}

//table XML
//QUERY ATAU PARAMS
# content
# id
###
GET http://localhost:5006/table-xml?content=
Content-Type: application/json
Authorization: Bearer {{token}}

//detail sensor
//QUERY ATAU PARAMS
# id
###
GET http://localhost:5006/detail-sensor?content=
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET http://localhost:5006/monitoring
Content-Type: application/json
Authorization: Bearer {{token}}
